config/routes.rb
Rails.application.routes.draw do
  # get 'upload/index'

    # root 'uploads#index'
   resources :uploads, only: [:index, :create, :destroy] do
     collection do
     get :list #list_uploads_url
       end
     end

   devise_for :users


 resources :gigs do
 	 resource :proposals, :reviews, :uploads,  expect: :index
 	collection do
 		get :search
 	end
 end
    root 'gigs#index'
    # get'/upload' => 'uploads#index'
    get'/mygigs' => 'gigs#mygigs'
    # get'/category' => 'gigs#category'
end

app/models/gig.rb
class Gig < ActiveRecord::Base
 has_many :proposals
 belongs_to :user
 belongs_to :category
 has_many   :abilities
 has_many   :reviews
 has_many   :skills, through: :abilities
 has_attached_file :image, styles: {large: "600x600>", medium: "300x300>", thumb: "150x150#"}
 validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
 geocoded_by :location
 after_validation :geocode

 def self.search(params)
 	if params[:category].present?
 		 gigs= Gig.where(Category_id: params[:category].to_i)
		 gigs= gigs.where("name like? or description like?","%#{params[:search]}%","%#{params[:search]}%")if params[:search].present?
		 gigs= gigs.near(params[:location], 20) if params[:location].present?
	else
	 gigs= Gig.where("name like? or description like?","%#{params[:search]}%","%#{params[:search]}%")if params[:search].present?
	 end	 
 	 gigs
 end
 def skill_list=(skills_string)
 	skill_names =skills_string.split(",").collect{ |s| s.strip.downcase}.uniq
 	new_or_found_skills= skill_names.collect{  |name| Skill.find_or_create_by(name: name)}
 	self.skills = new_or_found_skills
 	
 end
  def skill_list
  	self.skills.collect do |skill|
  	skill.name
  	end.join(",")		
  end
  def self.order_list(sort_order)
  	if sort_order== "newest" || sort_order.blank?
  		order(created_at: :desc)
   elsif sort_order=="name"			
  	order(name: :asc)
   else
   	order(created_at: :asc)
   end
  end
end

app/controllers/gigs_controller.rb
class GigsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :search, :show]
  def index
    @gigs= Gig.all.order_list(params[:sort_by]).page(params[:page]).per(5)
    @users = User.all

  end
  def new
  	@gig = Gig.new
  end
  def create
    @gig = Gig.new(gig_params)
    @gig.user= current_user
     if @gig.save
     redirect_to @gig
   else
    flash[:error] = @gig.erors.full_messages.to_sentence
    render :new
  end
  end

  def show
    @gig = Gig.find(params[:id])
    @proposals = @gig.proposals.order(created_at: :desc)
    @awarded_proposal= Proposal.where(id: @gig.awarded_proposal).first
    @reviews = Review.where(gig_id: @gig)
    if @reviews.blank?
      @avg_rating= 0
    else
      @avg_rating= @reviews.average(:rating).round(2)

    end
  end
  
  def edit
      @gig = Gig.find(params[:id])
      if current_user != @gig.user
      flash[:error]= "your are not the owner!"
      redirect_to @gig
    end   
  end
  def update
    @gig = Gig.find(params[:id])
    if current_user == @gig.user
    @gig.update(gig_params)
  else
     flash[:error]= "your are not the owner!"
   end
    redirect_to @gig  
  end
  def destroy
     @gig = Gig.find(params[:id])
      if current_user == @gig.user
     @gig.destroy
      else
     flash[:error]= "your are not the owner!"
   end
     redirect_to :mygigs
    
  end
  def search
    if params[:category].blank? && params[:search].blank?
      @gigs = Gig.all.order(created_at: :desc).page(params[:page]).per(5)
    else

    @gigs = Gig.search(params).page(params[:page]).per(5) 
  end
 end
  def mygigs
    @gigs= Gig.where(user_id: current_user).order(created_at: :asc)
    
  end
  private 
  def gig_params
  	params.require(:gig).permit(:name, :description, :budget, :location, :open, :category_id, :skill_list, :awarded_proposal,:image)
  end
end

app/views/gigs/_gig_form.html.erb
<div class="contents">
    <section id=post>
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-md-12">
                    <h3 class="sub-heading">Post a Task</h3>
                    <div class="content-inner-detail">
                        <%= simple_form_for :gig, url: gigs_path, html:{multipart: true} do |f| %>
                        <div class="row">
                            <div class="col-xs-12 col-md-6">
                                <div class="form-group">
                                    <%= f.label :name %>
                                    <%= f.text_field :name,   class: "form-control input-lg" %>
                                    <small class="help-block">Name of your job</small>
                                </div>
                            </div>
                            <div class="col-xs-12 col-md-6">
                                <div class="form-group">
                                    <%= f.label :budget %>
                                    <%= f.text_field :budget, class: "form-control input-lg" %>
                                    <small class="help-block">ex: $1,000 </small>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-xs-12 col-md-6">
                            <div class="form-group">
                                    <%= f.label :category_id %>
                                    <%= f.select :category_id,options_from_collection_for_select(Category.all, :id, :name),{},class: "form-control input-lg" %>
                                    <small class="help-block">Select the category for this Task</small>
                                </div>
                                </div>
                                <div class="col-xs-12 col-md-6">
                                <div class="form-group">
                                    <%= f.label :location %>
                                    <%= f.text_field :location,  class: "form-control input-lg" %>
                                    <small class="help-block">Randburg, Sandton, Melville, Booksburg, ect.)</small>
                                </div>
                            </div>

                        </div>

                        <div class="row">
                            <div class="col-xs-12 col-md-6">
                                <div class="form-group">
                                    <%= f.label :description %>
                                    <%= f.text_area :description, class: "form-control", rows: 10 %>
                                    <small class="help-block">Tell us everything about your job (website,virtual assistant, Handyman ,ect.)</small>
                                </div>
                            </div>
                            <div class="col-xs-12 col-md-6">
                                <div class="form-group">
                                    <%= f.label :image %>
                                    <%= f.file_field :image, class: "form-control" %>
                                    <small class="help-block">Tell us everything about your job (website,virtual assistant, Handyman ,ect.)</small>
                                </div>
                            </div>
                        </div>
                        <legend>List Skills required for this Task</legend>
                        <div class="form-group">
                        <%= f.text_area :skill_list, rows: 3, class: "form-control" %>
                        <small class="help-block">Separate skills with a comma. </small>
                            
                        </div>

                        <%= f.submit "Save Task", class: "btn btn-primary input-lg" %>
                        <% end %>
                        <br>
                        <br>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
<br>

app/views/gigs/category.html.erb
  <td  class="col-md-6">
      <p><%= link_to gig.name, gig %> <small class="label label-success"> <%= number_to_currency(gig.budget, precision: 0)  %></small></p>
       <p><%= h truncate(gig.description, length:500) %></p> 
       <p>Skills: <%= gig.skills.map{|s| s.name}.join(",") %></p>
 </td>                       

app/views/gigs/edit.html.erb
<%= render 'gigs/gig_form' %>

app/views/gigs/index.html.erb

<div class="banner-job">
    <div class="banner-overlay"></div>
    <div class="container text-center">
        <h1> We currently have <span class="orange"><strong> <%= @gigs.total_count %> </strong></span> tasks but only <span class="orange"><strong> <%= @users.count %> </strong></span> service providers </h1>
        <div style="padding-left: 100px">
            <%= form_tag search_gigs_path, method: :get do |f| %>
            <%= text_field_tag :search, nil, placeholder: "Example: Dstv Installation", class: "col-md-10 input-sm  input-lg" %>
            <%= submit_tag "search", class: " col-md-2 btn btn-primary btn-sm input-lg" %>
            <% end %>
            <br>  <br>  <br>
        </div>
        <ul class="banner-socail list-inline">
            <li><a href="#" title="Facebook"><i class="fa fa-facebook"></i></a></li>
            <li><a href="#" title="Twitter"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#" title="Google Plus"><i class="fa fa-google-plus"></i></a></li>
            <li><a href="#" title="Youtube"><i class="fa fa-youtube"></i></a></li>
        </ul><!-- banner-socail -->
    </div>
</div>
<%= render 'layouts/gig_listings' %>




app/views/gigs/mygigs.html.erb
<div class="contents">
<div class="container">
	<h3>M Tasks<small  class="pull-right"><%= @gigs.count %>Total</small></h3>
	<table class="table table-striped">
		<thead>
			<tr>
				<th class="text-center">Status</th>
				<th>Name</th>
				<th>Category</th>	
				<th>Budget</th>
				<th class="text-center">Proposals</th>
				<th colspan="3"></th>
			</tr>
		</thead>
		<tbody>
			<% @gigs.each do |gig| %>
			<tr>
				<td>
				 <% if gig.open %>
                   open
                   <%else%>
                   closed
				 <% end %>
				</td>
				<td><%= link_to gig.name, gig %></td>
				<td><%= gig.category.name %></td>
				<td><%= number_to_currency(gig.budget,precision: 0) %></td>
				<td class="text-center"><%= gig.proposals.count %></td>
				<td><%= link_to "Edit", edit_gig_path(gig), class: "btn btn-success"  %></td>
				<td><%= link_to "Delete", gig, method: :delete, data:{ confirm: "Are you sure?"} , class: "btn btn-danger" %></td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>	
</div>

app/views/gigs/new.html.erb
<%= render 'gigs/gig_form' %>

app/views/gigs/search.html.erb

<div class="banner-job">
    <div class="banner-overlay"></div>
    <div class="container text-center">
         <h1 class="col-sm-12 col-md-12 text-center" style="padding-top:40px">Your search resulted in  <span class="orange"><strong> <%= @gigs.total_count %> </strong></span> Tasks </h1>
        <div style="padding-left: 100px">
            <%= form_tag search_gigs_path, method: :get do |f| %>
            <%= text_field_tag :search, nil, placeholder: "Example: Dstv Installation", class: "col-md-10 input-sm  input-lg" %>
            <%= submit_tag "search", class: " col-md-2 btn btn-primary btn-sm input-lg" %>
            <% end %>
            <br>  <br>  <br>
        </div>
        <ul class="banner-socail list-inline">
            <li><a href="#" title="Facebook"><i class="fa fa-facebook"></i></a></li>
            <li><a href="#" title="Twitter"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#" title="Google Plus"><i class="fa fa-google-plus"></i></a></li>
            <li><a href="#" title="Youtube"><i class="fa fa-youtube"></i></a></li>
        </ul><!-- banner-socail -->
    </div>
</div>
<%= render 'layouts/gig_listings' %>




app/views/gigs/show.html.erb
<div class="container">
   <div class="row">
      <h3 class="sub-heading">Task Details
          <span class="pull-right"><small><%= link_to"&larr; All Tasks".html_safe, search_gigs_path %></small></span>
      </h3> 
    </div>
    <div class="col-xs-12 col-md-8">
        <div class="content-inner-details">
            <h1 class="sub-heading"><%=@gig.name %><span class="text-danger"></span></h1>
            <p><i class="fa fa-calendar"></i><%= @gig.created_at.strftime("%m %d, %Y") %>| <i class="fa fa-map-marker"></i><%= @gig.location.capitalize %>|<%= @gig.category.name %><span class="label label-success"><%= number_to_currency(@gig.budget, precision: 0) %></span><span class="prop-price serif italic star-rating" data-score=<%= @avg_rating %>></span>
            </p>
            <legend>Description</legend>
               <p><%= @gig.description %></p>
            <legend>Skills Wanted</legend>
            <ul>
                <% @gig.skills.each do |skill| %>
                    <li><%= skill.name %></li>
                <% end %>
            </ul>
            <legend>Image</legend>
            <%= image_tag @gig.image.url(:medium)  %>   
        </div>
    </div>

    <div class="col-xs-12 col-md-4">
         <div class="content-inner-detail">
            <legend>Submit a Proposal</legend>
            <% if user_signed_in? && @gig.user != current_user %>
               <%= simple_form_for :proposal, url: gig_proposals_path(@gig) do |f| %>
                  <div class="row">
                    <div class=" col-xs-12 col-md-12">
                        <div class="form-group">
                            <%= f.label :bid %>
                            <%= f.text_field :bid, class: "form-control input-lg" %>
                            <small class="help-block">Amount of your bid</small>  
                        </div>
                    </div>
                    <div class=" col-xs-12 col-md-12">
                        <div class="form-group">
                            <%= f.label :description %>
                            <%= f.text_area :description,row: 5 , class: "form-control input-lg" %>
                            <small class="help-block">Explain the skills needed for this Task</small>  
                        </div>
                    </div>
                  </div>
                  <%= f.submit "Submit Proposal", class: "btn btn-primary input-lg" %>
              <% end %>
              <% elsif @gig.user ==current_user && @gig.open == true %>
                 <h3 class="text_center">You can't bid on your own task!</h3>
               <% elsif @gig.open == false %>
               <h3 class="text_center">This Task is Closed!</h3>
               <% else %>
              <h3 class="text_center">Sign in to make a Bid</h3>
              <%= link_to 'sign in', new_user_session_path, class: "btn btn-primary form-control" %>
              <% end %>
                   
         </div>
    </div>
    <% if @awarded_proposal.present? %>
       <div class="col-xs-12 col-md-8">
           <h3 class="sub-heading">Accepted Proposal</h3>
              <div class="panel panel-default">
               <div class="panel-heading">
                   <div class="row">
                       <div class="col-md-4">
                           <h3 class="panel-title"><%= @awarded_proposal.user.name %> </h3>
                       </div>
                       <div class="col-md-4">
                          <h3 class="panel-title">
                            Bid:<%= number_to_currency(@awarded_proposal.bid, precision: 0) %>   
                          </h3>
                       </div>
                       <div class="col-md-4">
                           <h3 class="panel-title">
                            Posted:<%= @awarded_proposal.created_at.strftime("%B %d, %Y") %>
                           </h3>
                        </div>
                   </div>
               </div>
               <div class="panel-body">
                 <%= @awarded_proposal.description %>
               </div>
           </div>  
       </div>
    <% end %>

 <div class="col-xs-12 col-md-8">
 <hr>

 <%= link_to "Write a review", new_gig_reviews_path(@gig), class: "btn btn-small btn-success"%>
  <h3 class="sub-heading">Review</h3>
   <% if @reviews.blank? %>
   <p>No review yet!</p>
   <% else %>
    <table class="table">
      <thead>
        <th class="col-mid-3"></th>
        <th class="col-mid-9"></th>
      </thead>
      <tbody>
         <% @reviews.each do |review| %>
         <tr>
           <td>
             <h5><%= "#{review.user.name} #{review.user.first_name}" %></h5>
           </td>
           <td>
             <div class="clearfix star-rating" data-score=<%=review.rating %>></div>
              <%= review.comment %>
           </td>
         </tr>
         <% end %>
      </tbody>
    </table>
    
  <% end %>
</div>

 <div class="col-xs-12 col-md-8">
  <h3 class="sub-heading">Proposals</h3>
   <%if @proposals.present? %>
        <% @proposals.each do |proposal| %>
           <div class="panel panel-default">
               <div class="panel-heading">
                   <div class="row">
                       <div class="col-md-4">
                           <h3 class="panel-title"><%= proposal.user.name %> </h3>
                       </div>
                       <div class="col-md-4">
                          <h3 class="panel-title">
                            Bid:<%= number_to_currency(proposal.bid, precision: 0) %>   
                          </h3>
                       </div>
                       <div class="col-md-4">
                           <h3 class="panel-title">
                            Posted:<%= proposal.created_at.strftime("%B %d, %Y") %>
                           </h3>
                        </div>
                   </div>
               </div>
               <div class="panel-body">
                 <%= proposal.description %>
               </div>
               <% if current_user== @gig.user && @gig.awarded_proposal.blank? %>
               <div class="panel-footer">
                  <%= simple_form_for @gig, method: :put do |f| %>
                     <%= f.hidden_field :awarded_proposal, value: proposal.id %>
                     <%= f.hidden_field :open, value: false %>
                     <%= f.submit "Accept Proposal" %>
                  <% end %>
               </div>
               <% end %>
           </div>  
        <% end %>
     <% else %>
   <% end %>
 </div>
</div>
<br>
               
               