config/routes.rb
Rails.application.routes.draw do
  # get 'upload/index'

    # root 'uploads#index'
   resources :uploads, only: [:index, :create, :destroy] do
     collection do
     get :list #list_uploads_url
       end
     end

   devise_for :users


 resources :gigs do
 	 resource :proposals, :reviews, :uploads,  expect: :index
 	collection do
 		get :search
 	end
 end
    root 'gigs#index'
    # get'/upload' => 'uploads#index'
    get'/mygigs' => 'gigs#mygigs'
    # get'/category' => 'gigs#category'
end

app/views/layouts/_footer.html.erb
<!-- footer -->
	<footer id="footer" class="clearfix">
		<!-- footer-top -->
		<section class="footer-top clearfix">
			<div class="container">
				<div class="row">
					<!-- footer-widget -->
					<div class="col-sm-3">
						<div class="footer-widget">
							<h3>Quik Links</h3>
							<ul>
								<li><a href="#">About Us</a></li>
								<li><a href="#">Contact Us</a></li>
								<li><a href="#">Careers</a></li>
								<li><a href="#">All Cities</a></li>
								<li><a href="#">Help & Support</a></li>
								<li><a href="#">Advertise With Us</a></li>
							</ul>
						</div>
					</div><!-- footer-widget -->

					<!-- footer-widget -->
					<div class="col-sm-3">
						<div class="footer-widget">
							<h3>How to sell fast</h3>
							<ul>
								<li><a href="#">How to sell fast</a></li>
								<li><a href="#">Membership</a></li>
								<li><a href="#">Banner Advertising</a></li>
								<li><a href="#">Promote your ad</a></li>
								<li><a href="#">Jobs Delivers</a></li>
								<li><a href="#">FAQ</a></li>
							</ul>
						</div>
					</div><!-- footer-widget -->

					<!-- footer-widget -->
					<div class="col-sm-3">
						<div class="footer-widget social-widget">
							<h3>Follow us on</h3>
							<ul>
								<li><a href="#"><i class="fa fa-facebook-official"></i>Facebook</a></li>
								<li><a href="#"><i class="fa fa-twitter-square"></i>Twitter</a></li>
								<li><a href="#"><i class="fa fa-google-plus-square"></i>Google+</a></li>
								<li><a href="#"><i class="fa fa-youtube-play"></i>youtube</a></li>
							</ul>
						</div>
					</div><!-- footer-widget -->

					<!-- footer-widget -->
					<div class="col-sm-3">
						<div class="footer-widget news-letter">
							<h3>Newsletter</h3>
							<p>Jobs is Worldest leading Portal platform that brings!</p>
							<!-- form -->
							<form action="#">
								<input type="email" class="form-control" placeholder="Your email id">
								<button type="submit" class="btn btn-primary">Sign Up</button>
							</form><!-- form -->			
						</div>
					</div><!-- footer-widget -->
				</div><!-- row -->
			</div><!-- container -->
		</section><!-- footer-top -->

		<div class="footer-bottom clearfix text-center">
			<div class="container">
				<p>Copyright &copy; <a href="#">Zonke</a> 2017. Developed by <a href="http://devzoo.co.za/">raphael</a></p>
			</div>
		</div><!-- footer-bottom -->
	</footer><!-- footer -->
	

app/views/layouts/_gig_listings.html.erb
    
<div class="page">
    <div class="container">
                        
        <div class="section latest-jobs-ads">
            <div class="row">
                <div class="col-xs-12  col-md-3">

                    <h3 class="sub-heading">Advance Search</h3>
                    <div class="box">
                        <%= form_tag search_gigs_path, method: :get do |f| %>
                        <div class="form-group">
                            <label>Search</label>
                            <%= text_field_tag :search, nil, placeholder: "Plumber,Gardner, etc.", class: "form-control input-lg" %>
                        </div>
                        <div class="form-group">
                            <label>Category</label>
                            <%= select_tag :category, options_from_collection_for_select(Category.all, :id, :name), class: "form-control input-lg"%>
                        </div>
                        <div class="form-group">
                            <label>Location</label>
                            <%= text_field_tag :location, nil, placeholder: "Johannesburg, Pretoria, etc.", class: "form-control input-lg", autocomplete:"shipping street-address" %>
                        </div>
                        <%= submit_tag "search", class: " btn btn-primary input-lg btn-block" %>
                        <% end %>
                    </div>
                </div> 


                <!--  -->

                <div class="section latest-jobs-ads">
                          <div class="section-title tab-manu">
                        <h3 class="sub-heading">
                            Latest Task
                         <span class="pull-right">
                            <div class="dropdown">
                              <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                               Sort by
                               <span class="caret"></span>
                              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item" href="#"><%= link_to "Oldest", gigs_path(sort_by: "oldest") %></a>
                                <a class="dropdown-item" href="#"><%= link_to "Newest", gigs_path(sort_by: "newest" )%></a>
                                <a class="dropdown-item" href="#">Something else here</a>
                              </div>
                            </div>
                        </span>
                        </h3>
                       
                       
                    </div>
                    <div class="col-xs-12 col-sm-8 col-md-9 media">
                        <div class="job-list">
                            <div class="ad-info">

                                <table class="table ">
                                <thead>
                                <tr>
                                    <th class="">Photo</th>
                                    <th class="">Task Name</th>
                                    <th>Task Category</th>
                                    <th>Location & Date</th>   
                                </tr>
                               </thead>
                                    <tbody>
                                        <% @gigs.each do |gig| %>
                                        <tr>
                                        <td>
                                             <%= image_tag gig.image.url(:thumb), class: "gallery"  %> 
                                        </td>
                                            <td  class="col-md-3">
                                                <p> 
                                                    <strong><%= link_to gig.name, gig %></strong>  
                                                    <small class="label label-success">
                                                    <i class="fa fa-money"></i> 
                                                    <%= number_to_currency(gig.budget, precision: 0, :unit => "R")  %>
                                                    </small></p>

                                                <p><%= h truncate(gig.description, length:500) %></p> 
                                                <p>Skills: <%= gig.skills.map{|s| s.name}.join(",") %></p>
                                            </td>
                                            <td><i class="fa fa-tags"></i> <%= gig. category.name %></td>
                                            <td class="job-location">
                                                <p><i class="fa fa-calendar"></i> <%= gig.created_at.strftime ("%m %d,%Y")%></p>
                                                <p><i class="fa fa-map-marker"> </i> <%= gig.location %> </p>
                                            </td>
                                        </tr>
                                        <% end %>
                                    </tbody>
                                </table>
                               <div class="pull-right">
                                   <%= paginate @gigs %>
                               </div>
                        </div>
                    </div>
                </div>
             
                </div>
            </div>
        </div>
    </div>
</div>


app/views/layouts/_header.html.erb
<div class="navbar navbar-default navbar-static-top ">
    <div class="container">
        <div class="navbar-header">
            <buttom type="buttom" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#menu" aria-expanded="false">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </buttom>
                  <%= link_to image_tag("logo.png", alt: "logo"), root_path, class: 'navbar-brand' %>
        </div> <!-- end navbar-header -->
        <div class="collapse navbar-collapse" id="menu">
            <ul class="nav navbar-nav browse-jobs">
                <li class="btn btn-default navbar-btn">Browse all tasks  &raquo;</li>
                <%= link_to "Post task &raquo;".html_safe, new_gig_path, class: "btn btn-warning navbar-btn bg-orange" %>
            </ul>

            <div class=" navbar-right">
                <% if user_signed_in? %>
               
                <%= link_to "My Tasks", mygigs_path, class: "btn btn-success navbar-btn" %>
                <%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-info navbar-btn" %>
                <%= link_to "Sign Out", destroy_user_session_path, class: "btn btn-warning navbar-btn bg-orange" , method: :delete %>
                 <%= image_tag(current_user.avatar.url(:thumb), class: "round-image-50")  %>
                <% else %>
                <%= link_to "sign in", new_user_session_path, class: "btn btn-default navbar-btn" %>
                <%= link_to "sign up", new_user_registration_path, class: "btn btn-warning navbar-btn bg-orange" %>
                <% end %>
            </div>   
        </div> <!-- end menu div -->
    </div> <!-- end container div -->
</div>


 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Zonke24</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>
    <body>
        <%= render 'layouts/header' %>
        <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>">
            <a href="#" data-dismiss="alert" class="close">×</a>
            <ul>
                <li>
                    <%= value %>
                </li>
            </ul>
        </div>
        <% end %>
        <%= yield %>
        <%= render 'layouts/footer'%>
        <script>
          $('.star-rating').raty({
            path:'/assets',
            readOnly: true,
            score: function(){
              return $(this).attr('data-score');
            }
          });
        </script>
    </body>
</html>